name: Set environment
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
    job1:
        runs-on: ubuntu-latest
        outputs:
            env_name: ${{ steps.set_outputs.outputs.env_name }}
        steps:
            - id: set_outputs
              name: Set outputs
              run: |
                echo "env_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: Use outputs
              run: |
                echo "env_name: ${{ needs.job1.outputs.env_name }}"
          
