name: Set environment
on:
  push:
    branches:
      - dev/*
      - release/*
  workflow_dispatch:

permissions:
  contents: read

jobs:
    job1:
        runs-on: ubuntu-latest
        outputs:
            env_name: ${{ steps.set_outputs.outputs.env_name }}
        steps:
            - id: set_outputs
              name: Set outputs
              run: |
                echo "env_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: Use outputs
              run: |
                echo "env_name: ${{ needs.job1.outputs.env_name }}"

            - uses: winterjung/split@v2
              id: split
              with:
                msg: ${{ needs.job1.outputs.env_name }}
                separator: /

            - run: |
                echo "separated: ${{ steps.split.outputs._1 }}"

            - run: |
                echo "separated: ${{ steps.split.outputs._2 }}"
