name: Set environment
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment_name: ${{ steps.set_environment.outputs.environment_name }}
    steps:
      - id: set_environment
        run: |
          echo "environment_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT

  print-environment:
    runs-on: ubuntu-latest
    needs: set-environment
    steps:
      - run: |
          echo ${{ needs.set-environment.environment_name }}
          
