name: Set environment
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
    job1:
        runs-on: ubuntu-latest
        outputs:
            env_name: ${{ steps.set_outputs.outputs.env_name }}
        steps:
            - uses: winterjung/split@v2
              id: split
              with:
                msg: ${{ github.ref_name }}
                separator: /

            - id: set_outputs
              name: Set outputs
              run: |
                echo "env_name=${{ steps.split.outputs._1 }}" >> $GITHUB_OUTPUT

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: Use outputs
              run: |
                echo "env_name: ${{ needs.job1.outputs.env_name }}"

    job3:
        runs-on: ubuntu-latest
        needs: job1
        environment: ${{ needs.job1.outputs.env_name }}
        steps:
            - name: Use environment
              run: |
                echo "TEST_VAR: ${{ vars.TEST_VAR }}"

    job4:
        runs-on: ubuntu-latest
        steps:
          - name: az containerapp show
            uses: azure/CLI@v1
            with:
              inlineScript: |
                az containerapp show \
                  --resource-group rg-yone-containerapps-cicd \
                  --name ca-yone-containerapps-cicd \
                  --query properties.configuration.ingress.fqdn
  
