name: Set environment
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
    job1:
        runs-on: ubuntu-latest
        outputs:
            hoge: ${{ steps.set_outputs.outputs.hoge }}
        steps:
            - id: set_outputs
              name: Set outputs
              run: |
                echo "hoge=${{ github.ref }}" >> $GITHUB_OUTPUT

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: Use outputs
              run: |
                echo "hoge: ${{ needs.job1.outputs.hoge }}"
          
